// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlXsnhb5UiuWLRTeYA91Ib4tcCns_kQo',
    appId: '1:1020270970976:android:a806a0acaecec75a995b05',
    messagingSenderId: '1020270970976',
    projectId: 'projetipssi1',
    storageBucket: 'projetipssi1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDojkTSiwXgB3Q_LWnAvQEMJGlFQnFp86c',
    appId: '1:1020270970976:ios:9f6b54d6ac5d212b995b05',
    messagingSenderId: '1020270970976',
    projectId: 'projetipssi1',
    storageBucket: 'projetipssi1.appspot.com',
    iosClientId: '1020270970976-tojtpnnk58t5jsumma5tfmr285n5hpcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDojkTSiwXgB3Q_LWnAvQEMJGlFQnFp86c',
    appId: '1:1020270970976:ios:7018aa362820aeb3995b05',
    messagingSenderId: '1020270970976',
    projectId: 'projetipssi1',
    storageBucket: 'projetipssi1.appspot.com',
    iosClientId: '1020270970976-ubomfabggaa9oule9oiuh2pk6fbrbof2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233.RunnerTests',
  );
}
